module.exports = {
  // SESSION CONSTANTS
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  // ERROR CONSTANTS
  SET_ERRORS: "SET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  // COLLECTIONS
  COLLECTIONS_RECEIVED: "COLLECTIONS_RECEIVED",
  COLLECTION_RECEIVED: "COLLECTION_RECEIVED",
  COLLECTION_REMOVED: "COLLECTION_REMOVED"
}
